### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to MSP\NotifierQueue\Model\SendQueuedMessage::execute()

### ISSUE THREAD

**Issue by brian-labelle** [magespecialist/notifier-queue#1]
When sending queued messages from `bin/magento` with `msp:notifier:queue:send`, the following error occurs

```
Fatal error: Uncaught TypeError: Argument 1 passed to MSP\NotifierQueue\Model\SendQueuedMessage::execute() must be of the type integer, string given, called in /var/www/html/vendor/msp/module-notifier-queue/Model/SendQueue.php on line 62 and defined in /var/www/html/vendor/msp/module-notifier-queue/Model/SendQueuedMessage.php:104
Stack trace:
#0 /var/www/html/vendor/msp/module-notifier-queue/Model/SendQueue.php(62): MSP\NotifierQueue\Model\SendQueuedMessage->execute('1')
#1 /var/www/html/vendor/msp/module-notifier-queue/Command/SendQueue.php(58): MSP\NotifierQueue\Model\SendQueue->execute()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(242): MSP\NotifierQueue\Command\SendQueue->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /v in /var/www/html/vendor/msp/module-notifier-queue/Model/SendQueuedMessage.php on line 104
```

If I force `$message->getId()` to an int in [MSP\NotifierQueue\Model\SendQueue](https://github.com/magespecialist/notifier-queue/blob/master/Model/SendQueue.php), it works fine

**Comment by phoenix128** [comment]
Fixed in 0.1.4
